### ISSUE TITLE
User Calendar React 'Big Calendar'

### ISSUE THREAD

**Issue by jaclynmariefrench** [jaclynmariefrench/Spooktober_client#2]
## User Story

As a user, I should be able to view a calendar and eventually add movies to it, with full CRUD functionality.

### WHEN 
You open the project's client side

### THEN
You have the 'Big Calendar' plugin installed and set up for view.

## TO DO

- [x] install React 'Big Calendar' on client side

**Comment by gwynnemeeks** [comment]
This is a huge ticket that is going to take 2-3+ days. I suggest breaking it down into several smaller tickets or expanding the to-dos to account for the individual features of create, read, update, delete on the full stack.
