### ISSUE TITLE
Add movie to User Calendar

### ISSUE THREAD

**Issue by jaclynmariefrench** [jaclynmariefrench/Spooktober_client#6]
## User Story

As a user, I should be able to add searched movies to calendar by clicking the add button. 

### WHEN 
the user has searched movie
### THEN 
they should be able to add movie to calendar by clicking the add to calendar button

## TO DO

- [x] set up movie to be added on the client side
- [x] set up movie to be added to db on server side
- [x] set up movie to be deleted on the client side
- [x] set up movie to be deleted on the server side
- [ ] set up movie to be edited on the client side
- [ ] set up movie to be edited on the server side

**Comment by gwynnemeeks** [comment]
Your to dos are fine but your User story and AC doesn't talk about _how_ you're be adding the movie to the calendar. Is there a button involved?
